extended subgrid functionality
j-fu/ExtendableGrids.jl pull request #49
Opened 2024-06-18 14:36 UTC by chmerdon

extended subgrid features:
- new argument 'support' which can be ON_CELLS (default subgrid behaviour as before), ON_BFACES (default subgrid behaviour with boundary = true which also still works) and ON_FACES (new behaviour that generates a subgrid with faces)
- SubGrid type has now a parameter that knows the support relative to parent grid, removed BoundarySubGrid type
- removed get_facegrid, get_bfacegrid, get_edgegrid in derived.jl (that offer no new functionality compared to subgrid)

2024-06-18 15:12 UTC, j-fu commented
IMHO assemblytypes.jl needs to be included before subgrids.jl.

Generally, formally removing API (including keyword args) is a breaking change.
Unless we are really sure that nobody else uses this (I think  I use boundary=true) we should keep the old API, possibly with a deprecation warning.

2024-06-18 15:13 UTC, chmerdon commented
Yes, I am on it. Unfurtunately also som subgrid tests don't run through ^^

2024-06-18 15:23 UTC, chmerdon commented
Ok, now it should work... I messed up the old CoordinateSystem handling for codimension -1 grids

2024-06-18 19:19 UTC, j-fu commented on src/subgrid.jl
> +    @assert support in [ON_CELLS, ON_FACES, ON_BFACES] "value ($based) for 'support' is not allowed"
I think $based needs to be replaces by $support

2024-06-18 19:23 UTC, j-fu commented on src/subgrid.jl
> +abstract type SubGrid{based} <: ParentGridRelation where {based <: AssemblyType} end
May be `based` -> `support`?

2024-06-18 19:24 UTC, j-fu requested changes
One bug where `based` is still used.

2024-06-20 09:10 UTC, j-fu commented
Just checked with VoronoiFVM, tests are ok.

2024-06-20 09:45 UTC, merged